[general]
preferences = "example/participants_example.csv" #the file containing the choices and names
column.firstname = 1
column.surname = 2
column.city = 4 
results = "output/results.csv" #here are the results stored in a distributable format
stats = "output/stats.txt" #statistics of the run

[workshops]
columns = [8, 9, 10] #columns matching the first, second and third choice in the preferences file
capacities = "example/capacities_workshop_example.csv" #the file with max number of seats
cost.first = -10
cost.second = 0
cost.third = 1


[excursions]
columns = [5, 6, 7] #columns matching the first, second and third choice in the preferences file
capacities = "example/capacities_excursion_example.csv" #the file with max number of seats
cost.first = -10
cost.second = 0
cost.third = 1
